# wiki-flask configuration file

# this application is intended to be run using external auth providers. Yes, you 
# could probably hack it to support a more robust form of local authentication. 
# But then things might start to act erratically. Instead, you should configure
# an antilockout user here when you need to access the system in emergencies.
# Doing so will allow you to login at YOUR_DOMAIN_HERE/lockout. You should then
# use the username/password: `wikiflask/lockedout`.
enable_antilockout_user: false

# SMTP
enable_smtp: false
smtp_mail_server: null 
smtp_port: null 
smtp_username: null 
smtp_password: null 
smtp_from_address: null 

# SSO
enable_sso: false
saml_idp_entity_id: null
saml_idp_sso_url: null
saml_idp_slo_url: null
saml_idp_x509_cert: null
saml_strict: null
saml_debug: null
saml_name_id_format: null
saml_sp_x509_cert: null
saml_sp_private_key: null

# MongoDB
mongodb_host: localhost
mongodb_port: 27017
mongodb_user: null
mongodb_pw: null


# Look-and-feel
favicon: static/favicon.ico
site_logo: static/site_logo.png
max_title_len: 50
enable_page_audio: true